# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
#llm:
#  api_type: "openai"  # or azure / ollama / open_llm etc. Check LLMType for more options
#  model: "gpt-4-turbo-preview"  # or gpt-3.5-turbo-1106 / gpt-4-1106-preview
#  base_url: "https://api.openai.com/v1"  # or forward url / other llm url
#  api_key: "YOUR_API_KEY"

llm:
  timeout: 6000
  api_type: 'qianfan'
  api_key: 'ikmRlkz2R0pnBs0cuQ6XuD3c'
  secret_key: 'oypn1w7ZgoBqbKMfAeKEKhhdmrqBPcgo'
  model: 'ERNIE-Bot-4'

#llm:
#  api_type: ollama
#  base_url: 'http://127.0.0.1:11434/api'
#  model: 'llama2'

search:
  api_type: "serpapi"
  api_key: "e635caed78daec5f1ee210d7cf0064c717e7a44c93c18490f57fe939b2e4897e1"
#  api_key: "0b8f0150ac12bc6ec55bf652b0c6070c86fe8ae0f8bc8060c3fcca2cb799f83c"

#search:
#  api_type: "ddg"

browser:
  engine: "playwright"  # playwright/selenium
  browser_type: "firefox"  # playwright: chromium/firefox/webkit; selenium: chrome/firefox/edge/ie

#browser:
#  engine: "selenium"  # playwright/selenium
#  browser_type: "chrome"  # playwright: chromium/firefox/webkit; selenium: chrome/firefox/edge/ie